name: Test workflow_call

on:
  workflow_call:
    inputs:
      upload-artifact:
        type: boolean
        default: true

jobs:
  test-call-job:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "workflow_call works!"
