name: LUODA Test Build

on:
  push:
    branches:
      - main

jobs:
  test-call:
    uses: ./.github/workflows/flutter-build.yml
    with:
      upload-artifact: true
      upload-tag: "nightly"
    secrets: inherit
